services:
  insurance-service:
    build:
      context: .
      dockerfile: insurance-service/Dockerfile
    container_name: insurance-service
    ports:
      - "8080:8080"
    depends_on:
      db-insurance-service:
        condition: service_healthy
      insurance-registry-emulator:
        condition: service_started
      keycloak:
        condition: service_started
    environment:
      APP_SECURITY_JWT_JWK_SET_URI: http://keycloak:8080/realms/insurance/protocol/openid-connect/certs
      APP_SECURITY_JWT_ISSUER_URI: http://localhost:8082/realms/insurance
      APP_REGISTRY_BASE_URL: http://insurance-registry-emulator:8081
      APP_REGISTRY_API_KEY: registry-local-key

  insurance-registry-emulator:
    build:
      context: .
      dockerfile: insurance-registry-emulator/Dockerfile
    container_name: insurance-registry-emulator
    ports:
      - "8081:8081"
    depends_on:
      db-insurance-registry-emulator:
        condition: service_healthy
    environment:
      APP_REGISTRY_API_KEY: registry-local-key

  db-insurance-service:
    image: postgres:17.11
    container_name: db-insurance-service
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: insuranceservice123
      POSTGRES_DB: insurance_service
    ports:
      - "5434:5432"
    volumes:
      - db_insurance_service_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db_user -d insurance_service" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-insurance-registry-emulator:
    image: postgres:17.11
    container_name: db-insurance-registry-emulator
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: insuranceregistry123
      POSTGRES_DB: insurance_registry
    ports:
      - "5433:5432"
    volumes:
      - db_insurance_registry_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db_user -d insurance_registry" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.7
    command: start-dev --import-realm
    ports:
      - "8082:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json:ro

volumes:
  db_insurance_service_data:
  db_insurance_registry_data:

