server:
  port: 8081

spring:
  application:
    name: insurance-registry-emulator
  datasource:
    url: jdbc:postgresql://db-insurance-registry-emulator:5432/insurance_registry
    username: db_user
    password: insuranceregistry123
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

app:
  registry:
    api-key: ${APP_REGISTRY_API_KEY:registry-local-key}
